version: 0.2
phases:
    install:
        commands:
            - yum update -y
           

           
    build:
        commands:
            - echo Starting Java build at `date`
            - make
            
        finally:
            - echo Finished build of openh264
            
artifacts:
    files:
        - 'foo.bar'