version: 0.2
phases:
    install:
        commands:
            - sudo yum update -y
            - sudo yum install  make   libogg-devel   libsqlite-devel   libxml2-devel   libjpeg-devel   openssl-devel   ncurses-devel   libuuid-devel   libtool   autoconf  git  wget   gcc   gcc-c++   pkgconfig   nasm   patch   screen

           
    build:
        commands:
            - echo Starting Java build at `date`
            - make
            
        finally:
            - echo Finished build of openh264
            
artifacts:
    files:
        - 'foo.bar'